service: federated16steps

# Please ensure the serverless-openwhisk provider plugin is installed globally.
# $ npm install -g serverless-openwhisk
# ...before installing project dependencies to register this provider.
# $ npm install
provider:
  name: openwhisk
  # By default, the framework creates function versions for every deploy. This behavior
  # is optional, and can be turned off in cases where you don't invoke past versions by their qualifier
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  memory: 256 # Overwrite default memory size.
  timeout: 90 # Timeout in seconds
  overwrite: true # Can we overwrite deployed functions?

# define service wide environment variables
# OpenWhisk does not support using environment variables to pass
# custom parameters into the actions. Instead, of using environment variables, you can use default parameters on actions.
# Default parameters can be defined when you create or update an action. The platform stores these parameters internally
# and automatically includes them in the invocations parameters.
  workflowsLocation: /workflows.json
  owApiAuthKey: ${file(./accessKeys.json):openWhisk.owApiAuthKey}
  owApiAuthPassword: ${file(./accessKeys.json):openWhisk.owApiAuthPassword}
  awsAccessKeyId: ${file(./accessKeys.json):awsLambda.accessKeyId}
  awsSecretAccessKey: ${file(./accessKeys.json):awsLambda.secretAccessKey}

# you can add packaging information here
package:
  # individually: true
  exclude:
    - ./**
  include:
    - node_modules/cfc-lib/**
    - node_modules/uuid/**
    - node_modules/gaussian/**
    - workflows.json
    - handler1.js
    - handler2.js
    - handler3.js
    - handler4.js
    - handler9.js
    - handler10.js
    - handler11.js
    - handler12.js

functions:
  action1:
    handler: handler1.hello
    name: ${self:service}action1Handler
    annotations:
      web-export: true
    parameters:
      workflowsLocation: ${self:provider.workflowsLocation}
      owApiAuthKey: ${self:provider.owApiAuthKey}
      owApiAuthPassword: ${self:provider.owApiAuthPassword}
      awsAccessKeyId: ${self:provider.awsAccessKeyId}
      awsSecretAccessKey: ${self:provider.awsSecretAccessKey}
  action2:
    handler: handler2.hello
    name: ${self:service}action2Handler
    annotations:
      web-export: true
    parameters:
      workflowsLocation: ${self:provider.workflowsLocation}
      owApiAuthKey: ${self:provider.owApiAuthKey}
      owApiAuthPassword: ${self:provider.owApiAuthPassword}
      awsAccessKeyId: ${self:provider.awsAccessKeyId}
      awsSecretAccessKey: ${self:provider.awsSecretAccessKey}
  action3:
    handler: handler3.hello
    name: ${self:service}action3Handler
    annotations:
      web-export: true
    parameters:
      workflowsLocation: ${self:provider.workflowsLocation}
      owApiAuthKey: ${self:provider.owApiAuthKey}
      owApiAuthPassword: ${self:provider.owApiAuthPassword}
      awsAccessKeyId: ${self:provider.awsAccessKeyId}
      awsSecretAccessKey: ${self:provider.awsSecretAccessKey}
  action4:
    handler: handler4.hello
    name: ${self:service}action4Handler
    annotations:
      web-export: true
    parameters:
      workflowsLocation: ${self:provider.workflowsLocation}
      owApiAuthKey: ${self:provider.owApiAuthKey}
      owApiAuthPassword: ${self:provider.owApiAuthPassword}
      awsAccessKeyId: ${self:provider.awsAccessKeyId}
      awsSecretAccessKey: ${self:provider.awsSecretAccessKey}
  action9:
    handler: handler9.hello
    name: ${self:service}action9Handler
    annotations:
      web-export: true
    parameters:
      workflowsLocation: ${self:provider.workflowsLocation}
      owApiAuthKey: ${self:provider.owApiAuthKey}
      owApiAuthPassword: ${self:provider.owApiAuthPassword}
      awsAccessKeyId: ${self:provider.awsAccessKeyId}
      awsSecretAccessKey: ${self:provider.awsSecretAccessKey}
  action10:
    handler: handler10.hello
    name: ${self:service}action10Handler
    annotations:
      web-export: true
    parameters:
      workflowsLocation: ${self:provider.workflowsLocation}
      owApiAuthKey: ${self:provider.owApiAuthKey}
      owApiAuthPassword: ${self:provider.owApiAuthPassword}
      awsAccessKeyId: ${self:provider.awsAccessKeyId}
      awsSecretAccessKey: ${self:provider.awsSecretAccessKey}
  action11:
    handler: handler11.hello
    name: ${self:service}action11Handler
    annotations:
      web-export: true
    parameters:
      workflowsLocation: ${self:provider.workflowsLocation}
      owApiAuthKey: ${self:provider.owApiAuthKey}
      owApiAuthPassword: ${self:provider.owApiAuthPassword}
      awsAccessKeyId: ${self:provider.awsAccessKeyId}
      awsSecretAccessKey: ${self:provider.awsSecretAccessKey}
  action12:
    handler: handler12.hello
    name: ${self:service}action12Handler
    annotations:
      web-export: true
    parameters:
      workflowsLocation: ${self:provider.workflowsLocation}
      owApiAuthKey: ${self:provider.owApiAuthKey}
      owApiAuthPassword: ${self:provider.owApiAuthPassword}
      awsAccessKeyId: ${self:provider.awsAccessKeyId}
      awsSecretAccessKey: ${self:provider.awsSecretAccessKey}


# Add the serverless-openwhisk plugin
# https://github.com/serverless/plugins
plugins:
  - serverless-openwhisk